---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-${PROJECT_NAMESPACE}
  namespace: ${PROJECT_NAMESPACE}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-${PROJECT_NAMESPACE}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "extensions"
    resources:
      - "pods"
      - "routes"
      - "secrets"
      - "services"
      - "endpoints"
      - "ingresses"
      - "configmaps"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "patch"
      - "create"
      - "update"
      - "delete"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-rolebinding-${PROJECT_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: cluster-role-${PROJECT_NAMESPACE}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: sa-${PROJECT_NAMESPACE}
    namespace: ${PROJECT_NAMESPACE}
