# #################################################
# https://docs.gitlab.com/ee/ci/
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# https://docs.gitlab.com/ee/ci/yaml/README.html
# #################################################

# include:
#  - project: "template/gitlab-ci"
#    file: "/package/build-maven-artifacts.yml"
#    ref: master

# include:
#  - project: "template/gitlab-ci"
#    file: "/package/build-maven-docker.yml"
#    ref: master

# include:
#   - project: "template/gitlab-ci"
#     file: "/package/build-npm-docker.yml"
#     ref: lite

include:
  - project: "template/gitlab-ci"
    file: "/package/deploy-npm-kubernetes.yml"
    ref: master